# CI.yml
#
# Nessa pipeline, é verificado se o código está seguindo as boas práticas de desenvolvimento, como lint, testes e tipagem.
# Aqui também é verificado se todos os testes estão passando, tanto os unitários quanto os de integração.

name: NextJs 15 Boilerplate CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Cache Cypress
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Typescript check types
        run: pnpm check-types

      - name: Lint
        run: pnpm lint

      - name: Unit Tests with vitest
        run: pnpm test

      - name: Verify Cypress
        run: npx cypress verify

      - name: E2E Tests with Cypress
        run: |
          pnpm test:server
          npx cypress run

      - name: Build
        run: pnpm build
